Add implicit state support
triton-inference-server/tensorrt_backend pull request #19
Opened 2021-10-29 18:50 UTC by Tabrizian

Adds implicit state support for tensorrt backend.

2021-10-29 20:23 UTC, tanmayv25 requested changes

2021-10-29 20:23 UTC, tanmayv25 commented on src/tensorrt.cc
> +  // that the backend must return the output state to the client too.
I don't see any value in having these in64_t flags. These are just for detecting whether the unique outputs are state output and requested output.

How about adding these properties in `IOBindingInfo`? `is_state_tensor` and `is_requested_output_tensor`?

When parsing the buffers while placing outputs in response, we can utilize this information to call `ProcessTensor` or `ProcessStateTensor` acordingly.

2021-10-29 20:34 UTC, tanmayv25 commented on src/tensorrt.cc
> +        RETURN_IF_ERROR(InitializeExecuteOutputBinding(
Also, isn't the logic calling InitializeExecuteOutputBinding twice for outputs that are in state section?

2021-10-31 11:28 UTC, Tabrizian commented on src/tensorrt.cc
> +  // that the backend must return the output state to the client too.
Sounds good, fixed.

2021-10-31 11:29 UTC, Tabrizian commented on src/tensorrt.cc
> +        RETURN_IF_ERROR(InitializeExecuteOutputBinding(
Good catch, fixed.

2021-11-03 04:14 UTC, GuanLuo approved these changes

2021-11-03 21:00 UTC, merged