WIP: Add support for resetting buffer bindings
triton-inference-server/tensorrt_backend pull request #22
Opened 2021-11-30 04:27 UTC by CoderHam

2021-12-01 01:26 UTC, tanmayv25 requested changes

2021-12-01 01:26 UTC, tanmayv25 commented on src/tensorrt.cc
> +    // Only create binding buffers for payload if
Only record binding buffers in payload if ...

2021-12-01 01:26 UTC, tanmayv25 commented on src/tensorrt.cc
> +    std::vector<std::pair<void*, size_t>> buffer_binding_pairs_;
buffer_input_binding_pairs_

2021-12-01 03:42 UTC, tanmayv25 approved these changes

2021-12-02 18:39 UTC, tanmayv25 commented on src/tensorrt.cc
> +    size_t reset_buffer = atoi(reset_str);
reset_str will be NULL if TRITONSERVER_RESET_BINDING_BUFFERS is not set..

2021-12-02 18:39 UTC, tanmayv25 commented on src/tensorrt.cc
> +    size_t reset_buffer = atoi(reset_str);
More information here: https://man7.org/linux/man-pages/man3/getenv.3.html

2021-12-02 19:50 UTC, CoderHam commented on src/tensorrt.cc
> +    size_t reset_buffer = atoi(reset_str);
Fixed

2021-12-02 20:04 UTC, GuanLuo commented on src/tensorrt.cc
> +    const char* reset_str = getenv("TRITONSERVER_RESET_BINDING_BUFFERS");
Couldn't this be read only once on initialization?

2021-12-02 21:21 UTC, CoderHam commented on src/tensorrt.cc
> +    const char* reset_str = getenv("TRITONSERVER_RESET_BINDING_BUFFERS");
Done

2021-12-02 21:31 UTC, GuanLuo approved these changes

2021-12-02 21:38 UTC, tanmayv25 commented on src/tensorrt.cc
> +  reset_input_buffer_ = false;
Can you add a comment here saying TRITONSERVER_RESET_BINDING_BUFFERS is used only for testing purposes and should not be used otherwise.

2021-12-03 02:17 UTC, tanmayv25 approved these changes

2021-12-03 18:49 UTC, merged