Load Shared Libraries Dynamically
triton-inference-server/tensorrt_backend pull request #25
Opened 2022-03-10 17:52 UTC by dyastremsky

Allow user to load shared libraries via the backend configuration.

2022-03-24 00:37 UTC, tanmayv25 requested changes

2022-03-24 00:37 UTC, tanmayv25 commented on src/tensorrt.cc
> +#undef max
For consistency, define NOMINMAX before including windows.h . We do this everywhere else.
See here for example: https://github.com/triton-inference-server/server/blob/main/src/main.cc#L28

2022-03-24 00:37 UTC, tanmayv25 commented on src/tensorrt.cc
> +    std::cout << "Could not load plugin library: " << path << std::endl;
Is there a way to figure out error details of LoadLibraryA / LoadLibrary?

2022-03-24 00:37 UTC, tanmayv25 commented on src/tensorrt.cc
> +    std::cout << "Could not load plugin library: " << path << std::endl;
std::cerr ??

2022-03-24 00:37 UTC, tanmayv25 commented on src/tensorrt.cc
> +inline void
Instead of setting return type void, should we return TRITONSERVER_Error* and let the caller decide how to handle the error ?

2022-03-24 00:37 UTC, tanmayv25 commented on src/tensorrt.cc
> +    TRITONSERVER_ErrorNew(
We can log an error message when failing to register the plugin.

2022-03-24 00:37 UTC, tanmayv25 commented on src/tensorrt.cc
> +        LoadPlugin(plugin);
Take the error object from LoadPlugin and log the error message here(using LOG_MESSAGE is better). I think we can still continue without aborting.

2022-03-24 00:37 UTC, tanmayv25 commented on src/tensorrt.cc
> +    if (cmdline.Find("plugins", &value)) {
Shouldn't this be also a part of once_flag ? If there are multiple TensorRT models hosted in the server then it is not necessary to load the plugins with each load.

2022-03-24 04:29 UTC, dyastremsky commented on src/tensorrt.cc
> +    std::cout << "Could not load plugin library: " << path << std::endl;
Good question. Technically, yes. However, it can get messy. We'd likely want to use GetLastError, with the documentation here: https://docs.microsoft.com/en-us/windows/win32/debug/retrieving-the-last-error-code

A busy StackOverflow post with different solutions (and critiques of those solutions e.g. not supporting Unicode or Ansi/MBSC, creating memory leaks, potentially getting the error too late, etc.): https://stackoverflow.com/a/45565001. The link goes to what seems to be a good approach, though I think it'd require some research to be sure. We might still run into edge cases. Let me know if you think the benefit-risk tradeoff is worth it; if so, I'll implement it.

2022-03-24 05:14 UTC, dyastremsky commented on src/tensorrt.cc
> +    if (cmdline.Find("plugins", &value)) {
Is TRITONBACKEND_Initialize only called once? That seems to be what the backend header file implies, but I don't know if there's an exception. If so, could we get rid of once_flag in general?

If not, I can move the whole backend-config reading into the once_flag (probably in its own function).

2022-03-24 15:03 UTC, Tabrizian requested changes

2022-03-24 15:03 UTC, Tabrizian commented on src/tensorrt.cc
> +    std::cout << "Successfully loaded plugin library: " << path << std::endl;
I think we should be using the `LOG_MESSAGE` instead of `std::cout`.

2022-03-24 16:22 UTC, dyastremsky commented on src/tensorrt.cc
> +        LoadPlugin(plugin);
Great suggestion! Fixed.

2022-03-24 16:22 UTC, dyastremsky commented on src/tensorrt.cc
> +inline void
Updated. :)

2022-03-24 16:23 UTC, dyastremsky commented on src/tensorrt.cc
> +    std::cout << "Could not load plugin library: " << path << std::endl;
Good point! Switched it to logging as per your other feedback.

2022-03-24 16:28 UTC, dyastremsky commented on src/tensorrt.cc
> +#undef max
Done, thanks. Also updated to use the same ifdef flag for consistency (#ifdef _WIN32).

2022-03-24 16:38 UTC, dyastremsky commented on src/tensorrt.cc
> +    if (cmdline.Find("plugins", &value)) {
I confirmed that even with multiple models, the plugins are only loaded once.

It looks like this whole function only gets called once, so removing the once_flag seems like a good idea. Let me know if there's an edge or breaking case you can think of, otherwise I'll get delete it.

2022-03-24 16:51 UTC, Tabrizian approved these changes

2022-03-25 19:11 UTC, tanmayv25 commented on src/tensorrt.cc
> +    std::cout << "Could not load plugin library: " << path << std::endl;
Let's leave it as such for now. If it was simple we could have returned a more specific error but it is fine as it is now.

2022-03-25 19:18 UTC, tanmayv25 commented on src/tensorrt.cc
> +    if (cmdline.Find("plugins", &value)) {
>Is TRITONBACKEND_Initialize only called once? 

That's correct.

> I confirmed that even with multiple models, the plugins are only loaded once.

I was thinking something else.

> It looks like this whole function only gets called once, so removing the once_flag seems like a good idea. Let me know if there's an edge or breaking case you can think of, otherwise I'll delete it.

One edge case is that what if we have another backend (custom backend) that uses TRT plugins. So, for now let's leave the register part in the once_flag and load these plugins once. In summary let's leave them as such.

2022-03-25 19:19 UTC, tanmayv25 approved these changes

2022-03-25 19:28 UTC, CoderHam requested changes

2022-03-25 19:28 UTC, CoderHam commented on src/tensorrt.cc
> +         ", due to: " + dlerror())
Why not keep the error messages symmetric?

2022-03-25 19:28 UTC, CoderHam commented on src/tensorrt.cc
> +        pos = value_str.find(";");
What if there is only 1 plugin and no ';'?

2022-03-25 20:06 UTC, dyastremsky commented on src/tensorrt.cc
> +        pos = value_str.find(";");
std::string::npos gets returned. substr() will then return all characters until the end. It passes tests for both one and two plugins.

2022-03-25 20:09 UTC, dyastremsky commented on src/tensorrt.cc
> +         ", due to: " + dlerror())
Please see the conversation here: https://github.com/triton-inference-server/tensorrt_backend/pull/25#discussion_r835546722

Essentially, pulling the error for LoadLibrary/LoadLibraryA gets messy. We can do it, but the code would be more complicated and possibly introduce edge cases in terms of leaks and functionality. dlerror() is easy to call, so I think we should provide more information though since we can.

2022-03-25 20:09 UTC, CoderHam approved these changes

2022-03-29 23:46 UTC, GuanLuo commented on src/tensorrt.cc
> +  void* handle = dlopen(path.c_str(), RTLD_LAZY);
Shouldn't the `handle` be stored and release when the backend is being finalized?

2022-03-30 01:06 UTC, dyastremsky commented on src/tensorrt.cc
> +  void* handle = dlopen(path.c_str(), RTLD_LAZY);
Good point, thank you. We'll probably need to store a list of handles.

Since the core library has been moved into its own repo, we can also switch to using it here and get rid of the duplicated shared_library.h file in this and other repos. I'll switch to that approach.

2022-03-30 06:17 UTC, GuanLuo commented on src/tensorrt.cc
> +  void* handle = dlopen(path.c_str(), RTLD_LAZY);
I agree that we may expose the `shared_library.h` util for all other repos (and move it to `common` repo), but I incline to hold off for now and revisit it later: I am not sure about the special handling for exclusive access in `shared_library.h`. @deadeyegoodwin I wonder if you have some insight regarding this? I guess there is no way to guarantee it if the backends also interact with shared library.

2022-03-30 15:28 UTC, deadeyegoodwin commented on src/tensorrt.cc
> +  void* handle = dlopen(path.c_str(), RTLD_LAZY);
Do not make a backend dependent on any internal core library functions, only the TRITONBACKEND and TRITONSERVER functions can be used. As Guan mentioned we may more the utility into common repo at some point, but for now you should just copy what you need into the backend itself, and make sure to change the namespace, etc. to make the copy a full part of the backend.

2022-03-30 15:58 UTC, dyastremsky commented on src/tensorrt.cc
> +  void* handle = dlopen(path.c_str(), RTLD_LAZY);
Ah okay, so the core library is for the server exclusively, the common one is the one that's shared between repos. That makes sense. Thanks, I'll duplicate the necessary pieces.

2022-08-18 22:10 UTC, Tabrizian commented on src/filesystem.cc
> +}}}  // namespace triton::backend::tensorrt
New line

2022-08-18 22:10 UTC, Tabrizian commented on src/shared_library.cc
> +}}}  // namespace triton::backend::tensorrt
New line

2022-08-18 22:10 UTC, Tabrizian commented on src/shared_library.cc
> +  *handle = dlopen(path.c_str(), RTLD_LAZY);
Why we need to change the flag here? Can you add a comment explaining the same?

2022-08-18 22:41 UTC, dyastremsky commented on src/shared_library.cc
> +  *handle = dlopen(path.c_str(), RTLD_LAZY);
Thanks, reverted these flags and also addressed your newline comments.

I updated the flags while debugging to see if lazy loading was necessary, but looks not to be, so will use the same flags as we use elsewhere for dlopen again. Rerunning CI to confirm.

2022-08-19 02:14 UTC, tanmayv25 approved these changes

2022-08-19 23:16 UTC, merged