Adding examples of usage for TensorRT and its framework integrations
triton-inference-server/tensorrt_backend pull request #32
Opened 2022-05-04 19:16 UTC by tanayvarshney

Added guides examples to explain the workflow of optimizing models with TensorRT, Torch-TensorRT, and Tensorflow-TensorRT and deploying them on Triton

2022-05-07 01:24 UTC, tanmayv25 requested changes
I don't think these examples make sense in the TensorRT backend repository as these are so much more than TensorRT backend demo. TensorRT backend for Triton is very localized wrapper which Triton core uses to run inferences on TensorRT library.

You should add these examples here: https://github.com/NVIDIA/DeepLearningExamples
We link to these end-to-end examples here: https://github.com/triton-inference-server/server#additional-resources

If you need these examples to be more closer to Triton then I would suggest making github gists and pointing to it in our additional_resources section.  If even this does not work then I would suggest adding the examples directory to https://github.com/triton-inference-server/server.

2022-05-07 01:24 UTC, tanmayv25 commented on examples/TensorRT/README.md
> +
Note about matching versions.

2022-05-07 01:24 UTC, tanmayv25 commented on examples/TensorRT/README.md
> +python3 triton_client.py
Should show output triton_client here and everywhere.

2022-05-07 01:24 UTC, tanmayv25 commented on examples/TensorRT/config.pbtxt
> +]
New line.

2022-05-07 01:24 UTC, tanmayv25 commented on examples/TensorFlow_TensorRT/config.pbtxt
> +    format: FORMAT_NHWC
I don't think this is required. Please remove format from here and everywhere.

2022-05-07 01:24 UTC, tanmayv25 commented on examples/TensorRT/README.md
> +Before we proceed to the next step, it is important that we know the names of the "input" and "output" layers of your network, as these would be required by Triton. One easy way is to use `polygraphy
Should describe more about how you used polygraphy output and got to the config.pbtxt. 

Should also link to Triton's auto-complete-config feature through which you don't have to provide config.pbtxt for TRT models.
https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#auto-generated-model-configuration


You can include the link here and everywhere.

2022-05-07 01:24 UTC, tanmayv25 commented on examples/TensorRT/config.pbtxt
> +    format: FORMAT_NCHW
No format.

2022-05-07 01:24 UTC, tanmayv25 commented on examples/TensorRT/export_resnet_to_onnx.py
> +                  )
new line

2022-05-07 01:24 UTC, tanmayv25 commented on examples/TensorRT/triton_client.py
> +print(test_output_fin[:5])
new line

2022-05-07 01:24 UTC, tanmayv25 commented on examples/Torch_TensorRT/README.md
> +# Torch TensorRT to Triton
See my comments above to make similar changes.

2022-05-07 01:24 UTC, tanmayv25 commented on examples/Torch_TensorRT/config.pbtxt
> +]
new line

2022-05-07 01:24 UTC, tanmayv25 commented on examples/Torch_TensorRT/torch_trt_resnet50.py
> +torch.jit.save(trt_model, "model.pt")
new line

2022-05-07 01:24 UTC, tanmayv25 commented on examples/Torch_TensorRT/config.pbtxt
> +    format: FORMAT_NCHW
remove format

2022-05-09 16:51 UTC, tanayvarshney commented on examples/TensorFlow_TensorRT/tf_trt_resnet50.py
> +converter.save(output_saved_model_dir='resnet50_saved_model_TFTRT_FP32')
Not sure where you want the new line here. Can you help expand?

2022-05-09 18:26 UTC, tanayvarshney commented on README.md
> +The Triton backend for [TensorRT](https://github.com/NVIDIA/TensorRT). You can learn more about Triton backends in the [backend repo](https://github.com/triton-inference-server/backend). Documentatio
Re-ordered to make the intro section more concise. I can revert it to the original if needs be.

2022-05-09 19:10 UTC, tanmayv25 commented on README.md
> +The Triton backend for [TensorRT](https://github.com/NVIDIA/TensorRT). You can learn more about Triton backends in the [backend repo](https://github.com/triton-inference-server/backend). Documentatio
I would prefer to keep the order as is.

2022-05-09 19:12 UTC, tanmayv25 commented on examples/TensorFlow_TensorRT/README.md
> +docker run --gpus=1 --rm -p 8000:8000 -p 8001:8001 -p 8002:8002 -v /full/path/to/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:<xx.yy>-tf2-python-py3 tritonserver --model-reposit
the base py3 container works can definitely work with tf2 as long as  `--backend-config=tensorflow,version=2` is provided.

2022-05-11 00:33 UTC, tanmayv25 requested changes

2022-05-11 00:33 UTC, tanmayv25 commented on examples/TensorFlow_TensorRT/README.md
> +As might be apparent from the model structure above, each model requires a configuration file to spin up the server. We provide a sample of a `config.pbtxt`, which you can use for this specific examp
> As might be apparent from the model structure above, each model requires a configuration file to spin up the server.

This is not true. For TensorFlow SavedModel, Triton can obtain minimal model configuration by itself. I would remove this statement.
Add something like below:

> A sample model configuration of the model is included with this demo as `config.pbtxt`. If you are new to Triton, we highly encourage you to checkout out this [section of our documentation](https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md) for more details.

2022-05-11 00:33 UTC, tanmayv25 commented on examples/TensorFlow_TensorRT/README.md
> +Once you have the model repository setup, it is time to launch the triton server! You can do that with the docker command below.
Triton server

2022-05-11 00:33 UTC, tanmayv25 commented on examples/TensorFlow_TensorRT/config.pbtxt
> +    format: FORMAT_NHWC
Still not resolved. I don't think your clients are using the FORMAT specification.

2022-05-11 00:33 UTC, tanmayv25 commented on examples/TensorFlow_TensorRT/triton_client.py
> +# Quering the server
Querying

2022-05-11 00:33 UTC, tanmayv25 commented on examples/TensorRT/README.md
> +(Optional) If you don't have an ONNX model handy and just want to follow along, feel free to use this script:
still not resolved.

2022-05-11 00:33 UTC, tanmayv25 commented on examples/TensorRT/README.md
> +Before we proceed to the next step, it is important that we know the names of the "input" and "output" layers of your network, as these would be required by Triton. One easy way is to use `polygraphy
Polygrpahy -> Polygraphy

2022-05-11 00:33 UTC, tanmayv25 commented on examples/TensorRT/README.md
> +Before we proceed to the next step, it is important that we know the names of the "input" and "output" layers of your network, as these would be required by Triton. One easy way is to use `polygraphy
I don't think that is needed as you already are providing the config.pbtxt to the user. On the other hand, Triton itself can deduce the inputs and outputs when running with --strict-model-config=false. Hence, no need of polygraphy.

If you want to talk about it then please talk about how you used the output from polygraphy to construct the config.pbtxt. Otherwise this is not helpful.

2022-05-11 00:33 UTC, tanmayv25 commented on examples/TensorRT/README.md
> +polygraphy inspect model resnet50.engine --mode=basic
This is not helpful. What is the output of the above command? How did you use the results?

2022-05-11 00:33 UTC, tanmayv25 commented on examples/TensorRT/README.md
> +As might be apparent from the model structure above, each model requires a configuration file to spin up the server. We provide a sample of a `config.pbtxt`, which you can use for this specific examp
See my comments above about the model's config.pbtxt for TF-TRT. Triton does not require the user to provide config.pbtxt to host the TRT models.

2022-05-11 00:33 UTC, tanmayv25 commented on examples/TensorRT/README.md
> +
Still not resolved.

2022-05-11 00:33 UTC, tanmayv25 commented on examples/TensorRT/README.md
> +python3 triton_client.py
Still not resolved.

2022-05-11 00:33 UTC, tanmayv25 commented on examples/TensorRT/README.md
> +This README showcase how to deploy a simple resnet model accelerated by using TensorRT on NVIDIA Triton Inference Server. For an indepth explaination, refer this [blog](https://TODO_add_blog_link).
NVIDIA Triton Inference Server -> Triton Inference Server

2022-05-11 00:33 UTC, tanmayv25 commented on examples/Torch_TensorRT/README.md
> +# Torch TensorRT to Triton
Many of them are still not resolved.

2022-05-11 00:33 UTC, tanmayv25 commented on examples/Torch_TensorRT/README.md
> +This README showcase how to deploy a simple resnet model accelerated by using Torch TensorRT on NVIDIA Triton Inference Server. For an indepth explaination, refer this [blog](https://TODO_add_blog_li
NVIDIA Triton Inference Server -> Triton Inference Server

2022-05-11 00:33 UTC, tanmayv25 commented on examples/Torch_TensorRT/README.md
> +This README showcase how to deploy a simple resnet model accelerated by using Torch TensorRT on NVIDIA Triton Inference Server. For an indepth explaination, refer this [blog](https://TODO_add_blog_li
explanation

2022-05-11 00:33 UTC, tanmayv25 commented on examples/Torch_TensorRT/README.md
> +## Step 1: Optimize your model wtih Torch TensorRT
Torch-TensorRT

2022-05-11 00:33 UTC, tanmayv25 commented on examples/Torch_TensorRT/README.md
> +If you are unfamiliar with Torch TensorRT please refer this [video](https://www.youtube.com/watch?v=TU5BMU6iYZ0&ab_channel=NVIDIADeveloper). The first step in this pipeline is to accelerate your mode
Torch-TensorRT

2022-05-11 00:33 UTC, tanmayv25 commented on examples/Torch_TensorRT/README.md
> +If you are unfamiliar with Torch TensorRT please refer this [video](https://www.youtube.com/watch?v=TU5BMU6iYZ0&ab_channel=NVIDIADeveloper). The first step in this pipeline is to accelerate your mode
> If you are using PyTorch as you framework of choice for training,

What do you mean by that? Shouldn't the framework be PyTorch anyways for this demo to work?

2022-05-11 00:33 UTC, tanmayv25 commented on examples/Torch_TensorRT/README.md
> +For using Torch TensorRT, let's first pull our PyTorch docker container which comes installed with both TensorRT and Torch TensorRT. You may need to create an account and get the API key from [here](
Torch-TensorRT

2022-05-11 00:33 UTC, tanmayv25 commented on examples/Torch_TensorRT/README.md
> +We have already made sample to use Torch TensorRT: `torch_trt_resnet50.py`. For more examples visit our [Github Repository](https://github.com/NVIDIA/Torch-TensorRT/tree/master/notebooks).
> We have already made sample to use Torch TensorRT: `torch_trt_resnet50.py`.

Describe more about `sample`. What does it do? How does it generate `model.pt`

2022-05-11 00:33 UTC, tanmayv25 commented on examples/Torch_TensorRT/README.md
> +As might be apparent from the model structure above, each model requires a configuration file to spin up the server. We provide a sample of a `config.pbtxt`, which you can use for this specific examp
... TorchScript model requires a configuration file ...

2022-05-11 00:33 UTC, tanmayv25 commented on examples/Torch_TensorRT/README.md
> +python3 triton_client.py
Include the output of the client.

2022-05-19 21:40 UTC, rmccorm4 requested changes

2022-05-19 21:40 UTC, rmccorm4 commented on examples/TensorFlow_TensorRT/README.md
> +This README showcase how to deploy a simple ResNet model accelerated by using Tensorflow-TensorRT on Triton Inference Server. For an in-depth explanation, refer this [blog](https://TODO_add_blog_link
- showcase -> showcases
- refer this blog -> refer to this blog
- Fix **TODO_add_blog_link**

2022-05-19 21:40 UTC, rmccorm4 commented on examples/TensorFlow_TensorRT/README.md
> +For using Tensorflow-TensorRT, let's first pull our TensorFlow docker container, which comes installed with both TensorRT and Tensorflow-TensorRT. You may need to create an account and get the API ke
- our TensorFlow docker container -> the NGC TensorFlow Docker container

2022-05-19 21:40 UTC, rmccorm4 commented on examples/TensorFlow_TensorRT/README.md
> +We have already made a sample to use Tensorflow-TensorRT: `tf_trt_resnet50.py`. This sample downloads a ResNet model from Keras and then optimizes it with TensorFlow-TensorRT. For more examples, visi
- visit our Github Repository -> visit the TF-TRT Github repository

2022-05-19 21:40 UTC, rmccorm4 commented on examples/TensorFlow_TensorRT/README.md
> +A sample model configuration of the model is included with this demo as `config.pbtxt`. If you are new to Triton, we highly encourage you to check out this [section of our documentation](https://gith
This is duplicated twice. Only need the first half of this paragraph.

2022-05-19 21:40 UTC, rmccorm4 commented on examples/TensorFlow_TensorRT/README.md
> +docker run -it --gpus all -v /path/to/this/folder:/resnet50_eg nvcr.io/nvidia/tensorflow:<xx.xx>-tf2-py3
You should use 22.04 instead of <xx.xx> here for copy-paste purposes and to make sure the example works in the future even if something breaks in Triton/TF if 22.04 is the version that was tested.

2022-05-19 21:40 UTC, rmccorm4 commented on examples/TensorFlow_TensorRT/README.md
> +docker run --gpus all --rm -p 8000:8000 -p 8001:8001 -p 8002:8002 -v /full/path/to/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:<xx.yy>-py3 tritonserver --model-repository=/mode
1. You should use 22.04 instead of <xx.yy> here for copy-paste purposes and to make sure the example works in the future even if something breaks in Triton/TF; if 22.04 is the version that was tested. 

2. You should also point out that the version used to generate the TRT version should be the same as the version used for Triton.

2022-05-19 21:40 UTC, rmccorm4 commented on examples/TensorFlow_TensorRT/README.md
> +Download the image.
- Download the image. -> Download an example image to test inference.

2022-05-19 21:40 UTC, rmccorm4 commented on examples/TensorFlow_TensorRT/README.md
> +```
Why don't we use the SDK container here since it comes with the dependencies?

2022-05-19 21:40 UTC, rmccorm4 commented on examples/TensorFlow_TensorRT/README.md
> +These are confidence score along with the class of the image. To learn how to map these to the label names and more, refer to our [documentation](https://github.com/triton-inference-server/server/tre
- ~These are confidence score along with the class of the image~ -> The output format here is `<confidence_score>:<classification_index>`.
- ~https://github.com/triton-inference-server/server/tree/main/docs~ -> https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_classification.md

2022-05-19 21:40 UTC, rmccorm4 commented on examples/TensorFlow_TensorRT/triton_client.py
> +test_input = httpclient.InferInput("input_1", transoformed_img.shape, datatype="FP32")
~transoformed_img~ -> transformed_img -- everywhere in this file

2022-05-19 21:40 UTC, rmccorm4 commented on examples/TensorRT/README.md
> +This README showcase how to deploy a simple ResNet model accelerated by using TensorRT on Triton Inference Server. For an in-depth explanation, refer this [blog](https://TODO_add_blog_link).
- showcase -> showcases
- refer this blog -> refer to this blog
- Fix TODO_add_blog_link

2022-05-19 21:40 UTC, rmccorm4 commented on examples/TensorRT/README.md
> +docker run -it --gpus all -v /path/to/this/folder:/resnet50_eg nvcr.io/nvidia/pytorch:<xx.xx>-py3
1. You should use 22.04 instead of <xx.yy> here for copy-paste purposes and to make sure the example works in the future even if something breaks in Triton/TF; if 22.04 is the version that was tested.

2. You should also point out that the version used to generate the TRT version should be the same as the version used for Triton.

2022-05-19 21:40 UTC, rmccorm4 commented on examples/TensorRT/README.md
> +docker run -it --gpus all -v /path/to/this/folder:/trt_optimize nvcr.io/nvidia/tensorrt:<xx:yy>-py3
1. You should use 22.04 instead of <xx.yy> here for copy-paste purposes and to make sure the example works in the future even if something breaks in Triton/TF; if 22.04 is the version that was tested.

2. You should also point out that the version used to generate the TRT version should be the same as the version used for Triton.

2022-05-19 21:40 UTC, rmccorm4 commented on examples/TensorRT/README.md
> +As might be apparent from the model structure above, each model requires a configuration file to spin up the server. We provide a sample of a `config.pbtxt`, which you can use for this specific examp
Might be able to simplify this example using `tritonserver --strict-model-config=false` to autocomplete the TRT config file. I think Triton can completely autocomplete a simple TRT config file.

2022-05-19 21:40 UTC, rmccorm4 commented on examples/TensorRT/README.md
> ++-- resnet50
Consider naming these differently for each example, like "resnet50_trt", "resnet50_tftrt", "resnet50_torchtrt" in case a user tries multiple examples.

2022-05-19 21:40 UTC, rmccorm4 commented on examples/TensorRT/README.md
> +docker run --gpus all --rm -p 8000:8000 -p 8001:8001 -p 8002:8002 -v /full/path/to/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:<xx.yy>-py3 tritonserver --model-repository=/mode
1. You should use 22.04 instead of <xx.yy> here for copy-paste purposes and to make sure the example works in the future even if something breaks in Triton/TF; if 22.04 is the version that was tested.

2. You should also point out that the version used to generate the TRT version should be the same as the version used for Triton.

2022-05-19 21:40 UTC, rmccorm4 commented on examples/TensorRT/README.md
> +Download the image.
Download the image. -> Download an example image to test inference.

2022-05-19 21:40 UTC, rmccorm4 commented on examples/TensorRT/README.md
> +```
Why don't we use the SDK container here since it comes with the dependencies?

2022-05-19 21:40 UTC, rmccorm4 commented on examples/Torch_TensorRT/README.md
> +```
Why don't we use the SDK container here since it comes with the dependencies?

2022-05-19 21:40 UTC, rmccorm4 commented on examples/Torch_TensorRT/README.md
> +Download the image.
Download the image. -> Download an example image to test inference.

2022-05-19 21:40 UTC, rmccorm4 commented on examples/Torch_TensorRT/README.md
> +docker run -it --gpus all -v /path/to/this/folder:/resnet50_eg nvcr.io/nvidia/pytorch:<xx.xx>-py3
1. You should use 22.04 instead of <xx.yy> here for copy-paste purposes and to make sure the example works in the future even if something breaks in Triton/TF; if 22.04 is the version that was tested.

2. You should also point out that the version used to generate the TRT version should be the same as the version used for Triton.

2022-05-19 21:40 UTC, rmccorm4 commented on examples/Torch_TensorRT/README.md
> +docker run --gpus all --rm -p 8000:8000 -p 8001:8001 -p 8002:8002 -v /full/path/to/docs/examples/model_repository:/models nvcr.io/nvidia/tritonserver:<xx.yy>-py3 tritonserver --model-repository=/mode
1. You should use 22.04 instead of <xx.yy> here for copy-paste purposes and to make sure the example works in the future even if something breaks in Triton/TF; if 22.04 is the version that was tested.

2. You should also point out that the version used to generate the TRT version should be the same as the version used for Triton.

2022-05-19 21:40 UTC, rmccorm4 commented on examples/Torch_TensorRT/README.md
> ++-- resnet50
consider "resnet50_torchtrt"

2022-05-19 21:40 UTC, rmccorm4 commented on examples/TensorFlow_TensorRT/README.md
> ++-- resnet50
consider "resnet50_tftrt"

2022-05-19 21:40 UTC, rmccorm4 commented on examples/TensorRT/export_resnet_to_onnx.py
> +torch.hub._validate_not_a_forked_repo=lambda a,b,c: True
what is this for?

2022-05-19 21:40 UTC, rmccorm4 commented on examples/Torch_TensorRT/README.md
> +This README showcase how to deploy a simple ResNet model accelerated by using Torch-TensorRT on Triton Inference Server. For an in-depth explanation, refer this [blog](https://TODO_add_blog_link).
- showcase -> showcases
- refer this blog -> refer to this blog
- Fix **TODO_add_blog_link**

2022-05-19 21:40 UTC, rmccorm4 commented on examples/Torch_TensorRT/triton_client.py
> +transoformed_img = rn50_preprocess()
transoformed -> transformed everywhere in the script

2022-05-19 21:40 UTC, rmccorm4 commented on examples/Torch_TensorRT/torch_trt_resnet50.py
> +torch.hub._validate_not_a_forked_repo=lambda a,b,c: True
what is this for?

2022-05-19 21:40 UTC, rmccorm4 commented on examples/Torch_TensorRT/README.md
> +These are confidence scores along with the class of the image. To learn how to map these to the label names and more, refer to our [documentation](https://github.com/triton-inference-server/server/tr
- ~These are confidence score along with the class of the image~ -> The output format here is `<confidence_score>:<classification_index>`.
- ~https://github.com/triton-inference-server/server/tree/main/docs~ -> https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_classification.md

2022-05-19 21:40 UTC, rmccorm4 commented on examples/TensorRT/triton_client.py
> +transoformed_img = rn50_preprocess()
transoformed -> transformed everywhere in the script

2022-05-19 21:40 UTC, rmccorm4 commented on examples/TensorRT/README.md
> +These are confidence scores along with the class of the image. To learn how to map these to the label names and more, refer to our [documentation](https://github.com/triton-inference-server/server/tr
- ~These are confidence score along with the class of the image~ -> The output format here is `<confidence_score>:<classification_index>`.
- ~https://github.com/triton-inference-server/server/tree/main/docs~ -> https://github.com/triton-inference-server/server/blob/main/docs/protocol/extension_classification.md

2022-10-27 23:52 UTC, rmccorm4 commented
Closing for now based on comments and lack of activity. Can be re-opened or moved as needed.

2022-10-27 23:52 UTC, closed without merging