ifdef out kUINT8 based on TRT version
triton-inference-server/tensorrt_backend pull request #46
Opened 2022-09-09 18:58 UTC by krishung5

2022-09-09 19:08 UTC, nv-kmcgill53 approved these changes
Generated ticket specifying criteria for removal of the ifdefs: DLIS-4144

2022-09-09 19:16 UTC, GuanLuo commented on src/tensorrt_utils.cc
> +#define TENSORRT_VERSION version
Have you verified your change? "_" is missing here

2022-09-09 19:19 UTC, krishung5 commented on src/tensorrt_utils.cc
> +#define TENSORRT_VERSION version
Sorry for missing that. Added `_` last minute and somehow it's still compiled. It's fixed now.

2022-09-09 19:20 UTC, GuanLuo commented on src/tensorrt_utils.cc
> +// syntax.
Why can't be used? Because `NV_TENSORRT_VERSION` is defined as `constexpr`? Can you use https://github.com/NVIDIA/TensorRT/blob/main/include/NvInferVersion.h#L22-L23 ?

2022-09-09 19:26 UTC, rmccorm4 commented on src/tensorrt_utils.cc
> +#define TENSORRT_VERSION version
> Added _ last minute and somehow it's still compiled.

FYI, the definition won't do any checking. It will only have a compiler error if you tried to substitute the variable somewhere outside of an ifdef / directive.

```
#include <iostream>
#define MY_VAR non_existent_var

int main() {
    #if MY_VAR > 123
      std::cout << "Set correctly as some number";
    #else
      std::cout << "Set incorrectly";  // OK
      std::cout << "Set incorrectly as: " << MY_VAR;  // COMPILER ERROR UNDEFINED VARIABLE
    #endif

    return 0;
}
```

2022-09-09 19:32 UTC, krishung5 commented on src/tensorrt_utils.cc
> +// syntax.
It's because the `::` in this line: https://github.com/NVIDIA/TensorRT/blob/b55c4710ce01f076c26710a48879fcb2661be4a9/include/NvInferRuntimeCommon.h#L73

Used `NV_TENSORRT_MAJOR` and `NV_TENSORRT_MINOR `.

2022-09-09 19:32 UTC, rmccorm4 commented on src/tensorrt_utils.cc
> +#if ((NV_TENSORRT_MAJOR >= 8) && (NV_TENSORRT_MINOR >= 5))
this will break on TRT 9.0 if we don't remove it before then

2022-09-09 19:33 UTC, krishung5 commented on src/tensorrt_utils.cc
> +#if ((NV_TENSORRT_MAJOR >= 8) && (NV_TENSORRT_MINOR >= 5))
Ah right.. Let me change the logic here.

2022-09-09 19:36 UTC, krishung5 commented on src/tensorrt_utils.cc
> +#if ((NV_TENSORRT_MAJOR >= 8) && (NV_TENSORRT_MINOR >= 5))
Would simply use `[NV_TENSORRT_VERSION](https://github.com/NVIDIA/TensorRT/blob/b55c4710ce01f076c26710a48879fcb2661be4a9/include/NvInferRuntimeCommon.h#L82-L83)` be a better solution? It calculates the version and we can just compare it to the number "8500"?

2022-09-09 19:45 UTC, nv-kmcgill53 commented on src/tensorrt_utils.cc
> +#if ((NV_TENSORRT_MAJOR >= 8) && (NV_TENSORRT_MINOR >= 5))
I would be in favor of `NV_TENSORRT_VERSION`.

2022-09-09 22:38 UTC, GuanLuo commented on src/tensorrt_utils.cc
> +#if ((NV_TENSORRT_MAJOR >= 8) && (NV_TENSORRT_MINOR >= 5))
`NV_TENSORRT_VERSION` is `constexpr`, I am not experience with it so my question is can it replace preprocessor directive to control which part of the code to be hidden for compilation? The issue is that `kUINT8` is not available for older version so we don't want the compiler to do anything with that

2022-09-09 22:51 UTC, krishung5 commented on src/tensorrt_utils.cc
> +#if ((NV_TENSORRT_MAJOR >= 8) && (NV_TENSORRT_MINOR >= 5))
Sorry I don't follow what you mean.. We can use `NV_TENSORRT_VERSION` to determine if `kUINT8` should be hidden for compilation or not. The issue I'm facing is just that we cannot directly use `NV_TENSORRT_VERSION` like this: `#if (NV_TENSORRT_VERSION  >= 8500)` because colons are not acceptable in `#if` directive. We would need to have some workaround as the previous commit. I don't think whether `NV_TENSORRT_VERSION` is `constexpr` or not would affect anything here.

2022-09-09 23:03 UTC, GuanLuo commented on src/tensorrt_utils.cc
> +#if ((NV_TENSORRT_MAJOR >= 8) && (NV_TENSORRT_MINOR >= 5))
Okay, just make sure it can build with older TRT version (22.08 container)

2022-09-09 23:19 UTC, krishung5 commented
Reverted back to the previous commit which uses `NV_TENSORRT_VERSION`. I build TRT backend with 22.08 container locally and it's working. Waiting on the CI.

2022-09-09 23:19 UTC, nv-kmcgill53 approved these changes

2022-09-09 23:26 UTC, rmccorm4 commented on src/tensorrt_utils.cc
> +#if ((NV_TENSORRT_MAJOR >= 8) && (NV_TENSORRT_MINOR >= 5))
@krishung5 I think what Guan was asking is if something like this would compile with TRT < 8.5 using constexpr instead of ifdef, since constexpr is a compile-time concept.

(Could use the TRT constexpr variable instead of mine in this example)

```cpp
constexpr bool has_uint8 = false;

if (has_uint8) {
  dtype = nvinfer::dtype::kuint8
}
```

However, I think the answer is no, I believe the compiler would still complain the type doesn't exist for TRT < 8.5 even if using the constexpr.

2022-09-09 23:33 UTC, krishung5 commented on src/tensorrt_utils.cc
> +#if ((NV_TENSORRT_MAJOR >= 8) && (NV_TENSORRT_MINOR >= 5))
I see. Thanks for the clarification!

2022-09-09 23:43 UTC, nv-kmcgill53 commented on src/tensorrt_utils.cc
> +#if ((NV_TENSORRT_MAJOR >= 8) && (NV_TENSORRT_MINOR >= 5))
You are right that using a constexpr doesn't solve the issue. [Here is an example where the preprocessor allows the code to compile but the `constexpr` doesn't](https://godbolt.org/z/MbqTEPWzE). It has to do with when the compiler does the type checking, in the case of the C++ compiler it's done after the preprocessor. So any macros which are defined get substituted in as if it was explicitly written before compilation happens.

2022-09-10 01:04 UTC, nv-kmcgill53 requested changes
This change fails when using [TRT_VERSION 8.5.0.12](https://gitlab-master.nvidia.com/dl/dgx/tritonserver/-/jobs/44235796) but succeeds with [TRT_VERSION 8.4.2.4](https://gitlab-master.nvidia.com/dl/dgx/tritonserver/-/jobs/44232642).

2022-09-10 03:12 UTC, nv-kmcgill53 commented
Use this as the #define

`#define TENSORRT_VERSION ((NV_TENSORRT_MAJOR * 1000) + (NV_TENSORRT_MINOR * 100) + NV_TENSORRT_PATCH)`

2022-09-10 05:11 UTC, nv-kmcgill53 approved these changes

2022-09-12 16:57 UTC, merged