Support version compatibility for TensorRT models
triton-inference-server/tensorrt_backend pull request #74
Opened 2023-08-25 19:42 UTC by dyastremsky

Adds boolean backend parameter "version-compatible" to allow users to specify whether [version-compatible TensorRT models](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#version-compat) will be supported by Triton. This is an optional feature, as you must trust the plan model in this mode.

From [TensorRT documentation](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#version-compat):
"This causes a copy of the lean runtime to be added to the plan. When you subsequently deserialize the plan, TensorRT recognizes that it contains a copy of the runtime. It loads the runtime, and uses it to deserialize and execute the rest of the plan. Because this results in code being loaded and run from the plan in the context of the owning process, you should only deserialize trusted plans this way."

2023-08-25 21:03 UTC, tanmayv25 commented on src/loader.cc
> +        !runtime->get()->getEngineHostCodeAllowed()) {
Why do we need `getEngineHostCodeAllowed()` check?
Can't we directly call `setEngineCodeAllowed(ModelState::isVersionCompatible())`?

2023-08-25 21:08 UTC, tanmayv25 reviewed
We would need to include some tests for these changes.

2023-08-25 21:08 UTC, tanmayv25 commented on src/model_state.h
> +  static inline bool is_version_compatible_{false};
Why do we need this variable to be `static`? I wonder if we can have a use-case where we would want to load some models in version compatibility mode enabled and others with version compatibility disabled.

2023-08-25 21:36 UTC, dyastremsky commented on src/loader.cc
> +        !runtime->get()->getEngineHostCodeAllowed()) {
I thought it was important that we logged that version compatibility was enabled (especially since invalid backend parameter keys don't return an error), but wanted to make sure it only happened exactly once per-runtime to avoid user confusion or redundant logging. I was trying to think ahead to the next part of this feature where there would be multiple runtimes supported.

One alternate approach could be logging that the version compatibility backend parameter was received. That would also mean that the version compatibility logging statement would happen only once, which I think is better. I can switch to that approach, if that works for you.

2023-08-25 21:52 UTC, dyastremsky commented on src/model_state.h
> +  static inline bool is_version_compatible_{false};
I was doing this because the ModelState::CreateEngine call is static, but I realized that the logic made a lot more sense to put inside the logger's LoadPlan function. I think it would still be good to have this be static if we are doing this on a per-server basis.

As far as that use case, maybe. The main reason to disable version compatibility is for security. Doing it on a per-server basis makes sense to me. It's possible a user would have a use case though where they'd want us to allow the setting to be overridden from the model config. It seems like that's a security paradox though. You're essentially saying "I trust the user(s) loading models enough to know which models are safe, but I don't trust the user's model files to all be safe." That may be a long-term ask and doing it now could help with not worrying about backward compatibility later, though it might be premature as users might not want that or have that edge case. If you would rather me add that functionality before this PR gets merged, I'm happy to start a design. The reason for the small design is that I want to think through the best way to do this (e.g. will the backend need to have compatibility enabled then each model has to specifically enable it? what are the defaults?) and keep everything secure.

2023-08-25 22:04 UTC, dyastremsky commented
> Can you elaborate on this duplication issue?

By runtime duplication issue above, I mean that if I enabled version compatibility for our QA models, each model would have its own runtime and would thereby bloat the test size. After runtime reusability is added, it seems like more trouble than its worth to generate/save a runtime and adds its path to each of the non-performance test models' configurations. The benefit is that we could not worry about compatibility during the short period between releases when testing. I think it'd make more sense to generate new models and test version compatibility as a unit test. But perhaps I'm missing something that will change that tradeoff. In either case, I want to work on that feature next, so we should have an answer soon.

> Is there a problem with manually loading runtimes for each model? Shouldn't just making a `loadRuntime(<models_runtime_path>)` call allow it?

Thanks for this question. I'm outlining the approach that I'd put in a design below. I would get feedback on that design separately, as I need to think through some things as outlined in [this other PR comment](https://github.com/triton-inference-server/tensorrt_backend/pull/74#discussion_r1306174948).

We'd need to track the runtimes in a data structure. It's reasonably straightforward in my mind. We would add that data structure. Then, when a model config has a runtime path field, use it to get the runtime path. If that runtime is not already loaded, store it. Then, use that runtime for deserializing any models pointing to the same path. I wanted to make it a separate PR because it is discrete from what this one does, plus it modifies a bit of the managing of runtimes (going from one runtime to multiple).

2023-08-29 21:53 UTC, tanmayv25 commented on src/loader.cc
> +        !runtime->get()->getEngineHostCodeAllowed()) {
No issues. I think it is ok to log the setting where it is actually being configured. Offers better debug capability IMO.

2023-08-29 21:53 UTC, tanmayv25 commented on src/model_state.h
> +  static inline bool is_version_compatible_{false};
I see. Let's keep the version compatibility per-server basis setting.

2023-08-29 21:57 UTC, tanmayv25 commented
> I think it'd make more sense to generate new models and test version compatibility as a unit test. But perhaps I'm missing something that will change that tradeoff. In either case, I want to work on that feature next, so we should have an answer soon.

I think we should atleast have new models with/without runtime to cover these test cases in CI... We can think about moving all our CI tests to TensorRT version compatibility later.

2023-08-29 22:00 UTC, tanmayv25 requested changes

2023-08-29 22:00 UTC, tanmayv25 commented on README.md
> +* The `version-compatible` flag enables the loading of version-compatible TensorRT models. You must trust the
Can you link the TensorRT version compatibility feature for users to follow?

2023-08-30 00:07 UTC, dyastremsky commented on README.md
> +* The `version-compatible` flag enables the loading of version-compatible TensorRT models. You must trust the
Sure, thanks for suggesting this. Done.

2023-08-31 22:11 UTC, dyastremsky commented
> > I think it'd make more sense to generate new models and test version compatibility as a unit test. But perhaps I'm missing something that will change that tradeoff. In either case, I want to work on that feature next, so we should have an answer soon.
> 
> I think we should atleast have new models with/without runtime to cover these test cases in CI... We can think about moving all our CI tests to TensorRT version compatibility later.

Good point, Tanmay. Testing added here: https://github.com/triton-inference-server/server/pull/6255

2023-09-05 19:00 UTC, rmccorm4 commented on README.md
>  ##### --backend-config=tensorrt,coalesce-request-input=\<boolean\>,plugins="/path/plugin1.so;/path2/plugin2.so"
Add `version-compatible` flag to CLI example

2023-09-05 19:11 UTC, dyastremsky commented on README.md
>  ##### --backend-config=tensorrt,coalesce-request-input=\<boolean\>,plugins="/path/plugin1.so;/path2/plugin2.so"
Thanks! Added.

2023-09-05 19:41 UTC, rmccorm4 approved these changes

2023-09-05 22:01 UTC, krishung5 approved these changes

2023-09-05 22:05 UTC, tanmayv25 approved these changes

2023-09-05 23:09 UTC, merged

2023-09-12 01:19 UTC, oandreeva-nv commented on src/model_state.h
> +  static inline bool is_version_compatible_{false};
I think this broke or Windows pipeline: https://gitlab-master.nvidia.com/dl/dgx/tritonserver/-/jobs/68880138